# Generated by Django 3.2.12 on 2022-03-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
